<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Str;

class Board extends Model
{
    protected $fillable = [
        'board_name',
        'slug',
        'created_by',
        'updated_by',
    ];

    public function getRouteKeyName()
    {
        return 'slug';
    }

    public function createdUser()
    {
        return $this->belongsTo(User::class, 'created_by');
    }

    public function updatedUser()
    {
        return $this->belongsTo(User::class, 'updated_by');
    }

    protected static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub

        static::creating(function ($board){
            $board->slug = Str::slug($board->board_name);
            $board->created_by = Auth::id();
        });
        static::updating(function ($board){
            $board->slug = Str::slug($board->board_name);
            $board->updated_by = Auth::id();
        });
    }

}
