<?php

namespace App\Models;


use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Str;

/**
 * @method static create(array $array)
 * @method static where(string $string, int $int)
 */
class Institute extends Model
{
    protected $fillable = [
        'class_type_id',
        'institute_name',
        'slug',
        'created_by',
        'updated_by',
    ];


    public function classType()
    {
        return $this->belongsTo(ClassType::class, 'class_type_id');
    }

    public function getRouteKeyName()
    {
        return 'slug';
    }

    public function createdUser()
    {
        return $this->belongsTo(User::class, 'created_by');
    }

    public function updatedUser()
    {
        return $this->belongsTo(User::class, 'updated_by');
    }


    protected static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub

        static::creating(function ($institute) {
            $institute->slug = Str::slug($institute->institute_name);
            $institute->created_by = Auth::id();
        });
        static::updating(function ($institute) {
            $institute->slug = Str::slug($institute->institute_name);
            $institute->updated_by = Auth::id();
        });

    }


}
