<?php

namespace App\Models;


use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Str;

/**
 * @method static where(string $string, $section_name)
 * @method static create(array $all)
 * @method static latest()
 * @method static get(string $string)
 */
class Section extends Model
{
    protected $fillable = [
        'class_type_id',
        'section_name',
        'slug',
        'created_by',
        'updated_by',
    ];

    public function classType()
    {
        return $this->belongsTo(ClassType::class, 'class_type_id');
    }

    public function getRouteKeyName()
    {
        return 'slug';
    }

    public function createdUser()
    {
        return $this->belongsTo(User::class, 'created_by');
    }

    public function updatedUser()
    {
        return $this->belongsTo(User::class, 'updated_by');
    }


    protected static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub

        static::creating(function ($section) {
            $section->slug = Str::slug($section->section_name);
            $section->created_by = Auth::id();
        });
        static::updating(function ($section) {
            $section->slug = Str::slug($section->section_name);
            $section->updated_by = Auth::id();
        });

    }
}
