<?php

namespace App\Models;


use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Str;

/**
 * @method static create(array $all)
 * @method static where(string $string, $subject_name)
 */
class Subject extends Model
{
    protected $fillable = [
        'class_id',
        'section_id',
        'subject_name',
        'slug',
        'created_by',
        'updated_by',
    ];


    public function classType()
    {
        return $this->belongsTo(ClassType::class, 'class_id');
    }
    public function section()
    {
        return $this->belongsTo(Section::class, 'section_id');
    }

    public function getRouteKeyName()
    {
        return 'slug';
    }

    public function createdUser()
    {
        return $this->belongsTo(Subject::class, 'created_by');
    }

    public function updatedUser()
    {
        return $this->belongsTo(Subject::class, 'updated_by');
    }


    protected static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub

        static::creating(function ($subject) {
            $subject->slug = Str::slug($subject->subject_name);
            $subject->created_by = Auth::id();
        });
        static::updating(function ($subject) {
            $subject->slug = Str::slug($subject->subject_name);
            $subject->updated_by = Auth::id();
        });

    }
}
